"""urlhaus_entry

Revision ID: 818a3f82f172
Revises:
Create Date: 2026-04-15 06:10:17.609945+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "818a3f82f172"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urlhaus_entries",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("match_key", sa.String(), nullable=False),
        sa.Column("threat", sa.String(), nullable=True),
        sa.Column("tags", sa.String(), nullable=True),
        sa.Column("url_status", sa.String(), nullable=True),
        sa.Column("date_added", sa.DateTime(), nullable=True),
        sa.Column("last_online", sa.DateTime(), nullable=True),
        sa.Column("urlhaus_link", sa.String(), nullable=True),
        sa.Column("reporter", sa.String(), nullable=True),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_urlhaus_entries")),
    )
    with op.batch_alter_table("urlhaus_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_urlhaus_entries_host"), ["host"], unique=False)
        batch_op.create_index(
            "ix_urlhaus_entries_host_match_key", ["host", "match_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_urlhaus_entries_match_key"), ["match_key"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_urlhaus_entries_url"), ["url"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("urlhaus_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_urlhaus_entries_url"))
        batch_op.drop_index(batch_op.f("ix_urlhaus_entries_match_key"))
        batch_op.drop_index("ix_urlhaus_entries_host_match_key")
        batch_op.drop_index(batch_op.f("ix_urlhaus_entries_host"))

    op.drop_table("urlhaus_entries")
    # ### end Alembic commands ###
